"""Free vs Pro entitlement.

The free tier (trial) lets users test the app on a limited set of providers
and conversations before paying. A one-time purchase unlocks Pro.

  Free: 3 providers, 5 conversations per download.
  Pro ($24 one-time): all 8 providers, unlimited downloads.

Pro is unlocked with a license key issued by Paddle on purchase. The
key (format `TR-XXXXXXXX-XXXX-XXXX`) is generated by the
paddle-fulfillment-worker (Cloudflare Worker) when a Paddle
`transaction.completed` webhook fires, stored in KV, and emailed to the
customer via Courier. The app validates the key against the worker's
license verification endpoint. The entitlement is stored locally
(`license.json`) so the app stays local-first: a periodic best-effort
re-validation (`check_entitlement`) only revokes on a definitive
`valid=False` from the verification endpoint — an offline machine keeps
its Pro. The baked-in Pro edition (`totalrecalls.edition`) remains as an
internal build flag; public distribution ships the single free build + key.
"""

from __future__ import annotations

import hashlib
import json
import os
import re
import subprocess
import time
import urllib.parse
import urllib.request
import uuid

from totalrecalls.core.paths import appdata_dir
from totalrecalls.core.secure_storage import (
    SecureStorageError,
    delete as delete_secure_state,
    load_json,
    save_json,
)

# License verification endpoint (Cloudflare Worker `paddle-webhook` on
# totalrecalls.app). The worker stores keys in D1 and activates instances here:
# POST {"license_key", "instance_name"} → {"valid", "instance_id"}.
LICENSE_VERIFY_ENDPOINT = os.environ.get(
    "TR_LICENSE_VERIFY_ENDPOINT",
    "https://totalrecalls.app/api/licenses/verify",
)

# Identify ourselves explicitly on every verification call. Cloudflare in front
# of totalrecalls.app answers the default urllib User-Agent ("Python-urllib/3.x")
# with 403 Forbidden, which silently broke every activation until 2026-09-26.
USER_AGENT = os.environ.get(
    "TR_USER_AGENT", "TotalRecalls/1.0 (+https://totalrecalls.app)"
)
# Re-validate a stored entitlement at most once per hour, best-effort only:
# a stored Pro entitlement is never revoked because we are offline.
_REVALIDATE_INTERVAL = 3600

# Free-tier limits (mirrored in the UI and on the website).
FREE_PROVIDER_LIMIT = 3
FREE_CONVERSATION_LIMIT = 5
PRO_PRICE = "$24"

# The first FREE_PROVIDER_LIMIT provider ids are included free; the rest need Pro.
FREE_PROVIDER_IDS = ("perplexity", "chatgpt", "claude")

# License keys are issued by the paddle-fulfillment-worker (Cloudflare Worker)
# and have the format: TR-XXXXXXXX-XXXX-XXXX (uppercase alphanumerics).
# This regex checks only the shape; entitlement still requires an explicitly
# wired verifier.
_LICENSE_KEY_RE = re.compile(r"^[A-Z0-9]{2}-[A-Z0-9]{8}-[A-Z0-9]{4}-[A-Z0-9]{4}$")

_LICENSE_FILE = os.path.join(appdata_dir(), "license.json")
_MACHINE_ID_FILE = os.path.join(appdata_dir(), "machine-id.txt")


def _load_state() -> dict:
    try:
        return load_json(_LICENSE_FILE) or {}
    except SecureStorageError:
        return {}


def _save_state(state: dict) -> None:
    save_json(_LICENSE_FILE, state)


def _win32_query(name: str) -> str:
    """Best-effort WMI read of a single property (returns '' on any failure)."""
    if os.name != "nt":
        return ""
    try:
        out = subprocess.run(
            ["wmic", name, "get", "UUID"],
            capture_output=True, text=True, timeout=5,
        )
        for line in (out.stdout or "").splitlines():
            line = line.strip()
            if line and line.upper() != "UUID":
                return line
    except (OSError, subprocess.SubprocessError):
        pass
    return ""


def machine_identity() -> str:
    """A pseudonymous, stable-per-machine identifier.

    It is derived from hardware (motherboard UUID where available, MAC
    otherwise) and a per-install salt — no personal data, no account. The
    salt makes the value opaque to the verification endpoint: the endpoint
    only ever sees an opaque instance name, never hardware details.
    """
    salt = ""
    try:
        if os.path.exists(_MACHINE_ID_FILE):
            with open(_MACHINE_ID_FILE, "r", encoding="utf-8") as f:
                salt = f.read().strip()
    except OSError:
        salt = ""
    if not salt:
        salt = uuid.uuid4().hex
        try:
            with open(_MACHINE_ID_FILE, "w", encoding="utf-8") as f:
                f.write(salt)
        except OSError:
            pass  # read-only home: identity is still stable via the salt
    base = ""
    if os.name == "nt":
        base = _win32_query("win32_computersystemproductid")
    if not base:
        try:
            base = uuid.getnode()
        except Exception:
            base = os.environ.get("COMPUTERNAME", "unknown")
    digest = hashlib.sha256(f"{base}:{salt}".encode("utf-8")).digest()
    return "TR-" + digest[:10].hex().upper()


def _verify_post(payload: dict, timeout: int = 12) -> dict:
    """POST to the license verification endpoint. Returns the parsed JSON
    body. Raises ``OSError`` on network failure (distinct from a rejected
    key, which the endpoint reports with valid=False)."""
    data = json.dumps(payload).encode("utf-8")
    req = urllib.request.Request(
        LICENSE_VERIFY_ENDPOINT,
        data=data,
        headers={
            "Content-Type": "application/json",
            "Accept": "application/json",
            # Cloudflare in front of totalrecalls.app returns 403 to the default
            # urllib User-Agent ("Python-urllib/3.x"), which broke every
            # activation with no useful signal (verified 2026-09-26: same POST
            # → 200 with a browser/curl UA, 403 with urllib's). Always identify
            # ourselves explicitly.
            "User-Agent": USER_AGENT,
        },
        method="POST",
    )
    with urllib.request.urlopen(req, timeout=timeout) as resp:
        return json.loads(resp.read().decode("utf-8", "replace"))


def paddle_verifier(key: str, activate: bool = True) -> dict:
    """Store verifier for the Paddle license verification endpoint.

    ``activate=True`` registers this machine (the one-time activation on
    key entry); ``activate=False`` only validates (used for periodic
    best-effort re-checks of a stored entitlement). Returns a dict with
    ``valid`` boolean and optional ``instance_id``. Network failures raise.
    """
    payload = {"license_key": key}
    if activate:
        payload["instance_name"] = machine_identity()
    else:
        instance_id = str(_load_state().get("instance_id") or "")
        if instance_id:
            payload["instance_id"] = instance_id
    resp = _verify_post(payload)
    instance_id = resp.get("instance_id", "")
    valid = resp.get("valid", False)
    if activate and instance_id:
        state = _load_state()
        state["instance_id"] = instance_id
        _save_state(state)
    return {"valid": valid, "instance_id": instance_id}


def is_pro() -> bool:
    """True when a Pro license has been activated on this machine — or when
    this build is the unlocked buyer (Pro) edition, baked in at packaging time.

    This is a fast local check (no network): entitlement is established at
    activation time via the store verifier, and re-checked best-effort at
    startup through :func:`check_entitlement` so this never blocks the UI.
    """
    from totalrecalls.edition import is_pro_edition
    if is_pro_edition():
        return True
    return bool(_load_state().get("pro"))


def check_entitlement() -> bool:
    """Best-effort re-check of a stored Pro entitlement at startup.

    Rate-limited to one network call per hour. Offline / unreachable keeps
    the stored entitlement (grace); an explicit ``valid=False`` from the
    verification endpoint revokes it. Returns the effective Pro status. Safe
    there is no stored entitlement (returns False immediately).
    """
    state = _load_state()
    if not state.get("pro"):
        return False
    last = int(state.get("last_validated_at") or 0)
    if time.time() - last < _REVALIDATE_INTERVAL:
        return True
    try:
        resp = paddle_verifier(str(state.get("key") or ""), activate=False)
        ok = resp.get("valid", False)
    except (OSError, ValueError):
        ok = True  # offline / malformed response: keep the stored entitlement
    if not ok:
        # The endpoint says the key is not valid (disabled/expired). The
        # verification endpoint is the source of truth — clear the stale
        # local entitlement.
        try:
            delete_secure_state(_LICENSE_FILE)
        except SecureStorageError:
            pass
        return False
    try:
        state["last_validated_at"] = int(time.time())
        _save_state(state)
    except SecureStorageError:
        pass
    return True


def license_key() -> str:
    """The stored license key (or empty string)."""
    return str(_load_state().get("key") or "")


def tier_name() -> str:
    """Human-readable tier label: 'Pro' or 'Free'."""
    return "Pro" if is_pro() else "Free"


def validate_license_key_format(key: str) -> bool:
    """Check only the documented key shape (TR-XXXX-XXXX-XXXX); does not
    prove entitlement."""
    return bool(_LICENSE_KEY_RE.match((key or "").strip()))


def validate_license_key(key: str, verifier=None) -> bool:
    """Validate a key with an explicitly supplied store verifier.

    Credentials and an API contract are intentionally not embedded here.
    Without a verifier this returns ``False`` so a shaped string cannot
    unlock production builds by itself.
    """
    key = (key or "").strip()
    if not validate_license_key_format(key) or verifier is None:
        return False
    try:
        return bool(verifier(key))
    except Exception:
        return False


def activate_license(key: str, verifier=None) -> dict:
    """Validate ``key`` and persist Pro, or explain why activation failed.

    With no explicit ``verifier`` this uses the Paddle license verification
    endpoint: a one-time activation that registers this machine as an
    instance. A network failure is reported as such so the user can retry;
    a key the endpoint rejects is reported as unverified. An explicit
    ``verifier`` (tests or an alternative store) bypasses the network
    entirely.
    """
    key = (key or "").strip()
    if not key:
        return {"ok": False, "message": "Enter a license key."}
    if not validate_license_key_format(key):
        return {"ok": False, "message": "That license key is not a valid TotalRecalls key."}
    if verifier is not None:
        # Explicit verifier (tests / alternative store): no network.
        if not validate_license_key(key, verifier=verifier):
            return {"ok": False, "message": "That license key could not be verified."}
        try:
            _persist_pro(key)
        except SecureStorageError:
            return {
                "ok": False,
                "message": "Unable to securely save the license on this device.",
            }
        return {"ok": True, "message": "Pro unlocked — all 8 providers, unlimited downloads."}
    # Default: Paddle verification endpoint (one-time, registers this machine).
    try:
        resp = paddle_verifier(key, activate=True)
        ok = resp.get("valid", False)
    except (OSError, ValueError):
        return {
            "ok": False,
            "message": "Could not reach the license server. Check your internet connection and try again.",
        }
    if not ok:
        return {"ok": False, "message": "That license key could not be verified."}
    try:
        _persist_pro(key)
    except SecureStorageError:
        return {
            "ok": False,
            "message": "Unable to securely save the license on this device.",
        }
    return {"ok": True, "message": "Pro unlocked — all 8 providers, unlimited downloads."}


def _persist_pro(key: str) -> None:
    """Persist a verified Pro entitlement (raises SecureStorageError)."""
    now = int(time.time())
    state = {
        "pro": True,
        "key": key,
        "activated_at": now,
        "last_validated_at": now,
    }
    instance_id = str(_load_state().get("instance_id") or "")
    if instance_id:
        state["instance_id"] = instance_id
    _save_state(state)


def deactivate_license() -> dict:
    """Clear the local entitlement and, best-effort, free this machine's
    activation slot on the verification endpoint (support / moving machines).
    """
    state = _load_state()
    key = str(state.get("key") or "")
    instance_id = str(state.get("instance_id") or "")
    slot_result = "unknown"
    if key and instance_id:
        try:
            _verify_post({"license_key": key, "instance_id": instance_id, "action": "deactivate"})
            slot_result = "freed"
        except (OSError, ValueError):
            slot_result = "offline"
    try:
        delete_secure_state(_LICENSE_FILE)
    except SecureStorageError:
        return {"ok": False, "message": "Unable to remove the local license safely."}
    if slot_result == "freed":
        return {"ok": True, "message": "License removed. This machine's activation slot is freed."}
    if slot_result == "offline":
        return {
            "ok": True,
            "message": "License removed on this device. We could not reach the license "
                       "server to free the activation slot — email support if you need it back.",
        }
    return {"ok": True, "message": "License removed."}


def provider_is_free(provider_id: str) -> bool:
    """True when `provider_id` is part of the free tier."""
    return provider_id in FREE_PROVIDER_IDS


def provider_is_pro_only(provider_id: str) -> bool:
    """True when `provider_id` requires a Pro license."""
    return provider_id not in FREE_PROVIDER_IDS
